name: scicomp
channels:
  - conda-forge
  - defaults
  - pytorch
  - qiskit
dependencies:
  # Python version
  - python>=3.9

  # Core scientific computing
  - numpy>=1.21.0
  - scipy>=1.7.0
  - matplotlib>=3.4.0
  - pandas>=1.3.0
  - h5py>=3.3.0
  - tqdm>=4.61.0
  - joblib>=1.0.0
  - sympy>=1.8.0

  # Visualization
  - seaborn>=0.11.0
  - plotly>=5.0.0
  - bokeh>=2.3.0

  # Machine Learning
  - scikit-learn>=1.0.0
  - tensorflow>=2.8.0
  - pytorch>=1.11.0
  - torchvision
  - torchaudio

  # High-performance computing
  - numba>=0.56.0
  - cython>=0.29.0
  - openblas
  - mkl
  - mkl-service

  # Development tools
  - jupyter
  - ipykernel
  - notebook
  - jupyterlab
  - pytest>=6.2.0
  - pytest-cov>=2.12.0
  - black>=21.6b0
  - flake8>=3.9.0
  - mypy>=0.910

  # Documentation
  - sphinx>=4.0.0
  - sphinx_rtd_theme
  - nbsphinx

  # Additional scientific tools
  - networkx>=2.6.0
  - opt-einsum>=3.3.0
  - sparse>=0.13.0
  - xarray
  - netcdf4
  - hdf5
  - zarr

  # Materials science (conda-forge)
  - ase>=3.22.0
  - spglib
  - phonopy

  # pip-only packages
  - pip
  - pip:
    - qiskit>=0.34.0
    - pennylane>=0.22.0
    - dwave-ocean-sdk>=4.0.0
    - pymatgen>=2022.0.0
    - cirq>=0.13.0
    - pytorch-lightning>=1.6.0
    - wandb>=0.12.0
    - optuna>=2.10.0
    - memory-profiler>=0.58.0
    - line-profiler>=3.3.0
    - pre-commit>=2.13.0